-- Owner-controlled operations: no tasks are generated by roles, checklists,
-- or shift start. Every visible employee task must be explicitly assigned by
-- the owner. Existing unfinished/generated work is cleared for a clean start;
-- completed records remain as immutable operational history.

alter table public.staff_profiles
  add column if not exists scheduled_end time;

-- Keep the existing call sites stable while disabling every automatic task.
create or replace function private.seed_shift_tasks(
  p_user_id uuid,
  p_role public.staff_role,
  p_branch_id uuid,
  p_shift_date date,
  p_lang text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  return;
end;
$$;

delete from public.tasks where not completed;
delete from public.checklist_templates;
delete from public.task_definitions;

create or replace function private.owner_assign_custom_task_impl(
  p_user_id uuid,
  p_employee_ids uuid[],
  p_task_date date,
  p_title text,
  p_notes text,
  p_is_required boolean,
  p_requires_photo boolean,
  p_requires_note boolean,
  p_response_type text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner public.staff_profiles;
  v_employee_id uuid;
  v_result jsonb;
  v_assigned integer := 0;
  v_duplicates integer := 0;
begin
  v_owner := private.require_staff(p_user_id);
  if v_owner.role <> 'owner' then
    raise exception 'Only owners can assign tasks' using errcode = '42501';
  end if;
  if p_task_date is null or p_employee_ids is null
    or cardinality(p_employee_ids) not between 1 and 100
  then
    return jsonb_build_object('ok', false, 'code', 'assignment_invalid');
  end if;
  if (select count(*) from public.staff_profiles
      where user_id = any(p_employee_ids) and is_active
        and role not in ('owner', 'manager', 'shift_manager')) <> cardinality(p_employee_ids)
  then
    return jsonb_build_object('ok', false, 'code', 'employee_invalid');
  end if;

  foreach v_employee_id in array p_employee_ids loop
    v_result := private.owner_assign_task_impl(
      p_user_id, v_employee_id, p_task_date, p_title,
      p_is_required, p_requires_photo, 0, p_notes,
      p_requires_note, p_response_type
    );
    if (v_result->>'ok')::boolean then
      v_assigned := v_assigned + 1;
    elsif v_result->>'code' = 'duplicate_task' then
      v_duplicates := v_duplicates + 1;
    else
      return v_result;
    end if;
  end loop;
  return jsonb_build_object('ok', true, 'assigned', v_assigned, 'duplicates', v_duplicates);
end;
$$;

create or replace function public.owner_assign_custom_task(
  p_employee_ids uuid[],
  p_task_date date,
  p_title text,
  p_notes text default null,
  p_is_required boolean default true,
  p_requires_photo boolean default false,
  p_requires_note boolean default false,
  p_response_type text default 'completion'
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.owner_assign_custom_task_impl(
    (select auth.uid()), p_employee_ids, p_task_date, p_title, p_notes,
    p_is_required, p_requires_photo, p_requires_note, p_response_type
  );
$$;

create or replace function private.owner_delete_assigned_task_impl(
  p_user_id uuid,
  p_task_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner public.staff_profiles;
  v_deleted uuid;
begin
  v_owner := private.require_staff(p_user_id);
  if v_owner.role <> 'owner' then
    raise exception 'Only owners can delete assigned tasks' using errcode = '42501';
  end if;
  delete from public.tasks
  where id = p_task_id and task_type = 'general_duty' and not completed
  returning id into v_deleted;
  if v_deleted is null then
    return jsonb_build_object('ok', false, 'code', 'task_not_editable');
  end if;
  return jsonb_build_object('ok', true, 'task_id', v_deleted);
end;
$$;

create or replace function public.owner_delete_assigned_task(p_task_id uuid)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.owner_delete_assigned_task_impl((select auth.uid()), p_task_id);
$$;

create or replace function private.owner_set_staff_schedule_impl(
  p_user_id uuid,
  p_employee_id uuid,
  p_scheduled_start time,
  p_scheduled_end time
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner public.staff_profiles;
  v_employee public.staff_profiles;
begin
  v_owner := private.require_staff(p_user_id);
  if v_owner.role <> 'owner' then
    raise exception 'Only owners can set staff schedules' using errcode = '42501';
  end if;
  if p_scheduled_start is null or p_scheduled_end is null
    or p_scheduled_start = p_scheduled_end
  then
    return jsonb_build_object('ok', false, 'code', 'schedule_invalid');
  end if;
  update public.staff_profiles
  set scheduled_start = p_scheduled_start, scheduled_end = p_scheduled_end
  where user_id = p_employee_id and is_active
    and role not in ('owner', 'manager', 'shift_manager')
  returning * into v_employee;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'employee_invalid');
  end if;
  return jsonb_build_object(
    'ok', true,
    'employee_id', v_employee.user_id,
    'scheduled_start', v_employee.scheduled_start,
    'scheduled_end', v_employee.scheduled_end
  );
end;
$$;

create or replace function public.owner_set_staff_schedule(
  p_employee_id uuid,
  p_scheduled_start time,
  p_scheduled_end time
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.owner_set_staff_schedule_impl(
    (select auth.uid()), p_employee_id, p_scheduled_start, p_scheduled_end
  );
$$;

revoke all on function private.owner_assign_custom_task_impl(uuid,uuid[],date,text,text,boolean,boolean,boolean,text) from public, anon;
grant execute on function private.owner_assign_custom_task_impl(uuid,uuid[],date,text,text,boolean,boolean,boolean,text) to authenticated;
revoke all on function public.owner_assign_custom_task(uuid[],date,text,text,boolean,boolean,boolean,text) from public, anon;
grant execute on function public.owner_assign_custom_task(uuid[],date,text,text,boolean,boolean,boolean,text) to authenticated;
revoke all on function private.owner_delete_assigned_task_impl(uuid,uuid) from public, anon;
grant execute on function private.owner_delete_assigned_task_impl(uuid,uuid) to authenticated;
revoke all on function public.owner_delete_assigned_task(uuid) from public, anon;
grant execute on function public.owner_delete_assigned_task(uuid) to authenticated;
revoke all on function private.owner_set_staff_schedule_impl(uuid,uuid,time,time) from public, anon;
grant execute on function private.owner_set_staff_schedule_impl(uuid,uuid,time,time) to authenticated;
revoke all on function public.owner_set_staff_schedule(uuid,time,time) from public, anon;
grant execute on function public.owner_set_staff_schedule(uuid,time,time) to authenticated;
